import type { SubjectDefinition } from "./model";

export const TRANSFER_SUBJECT_ID = "__TRANSFER__";

export const FIXED_SUBJECTS: SubjectDefinition[] = [
  { subjectId: "INCOME_MEMBERSHIP_FEE", label: "会費", categoryId: "income_membership_fee", type: "income", sortOrder: 10 },
  { subjectId: "INCOME_DONATION", label: "寄付金", categoryId: "income_donation", type: "income", sortOrder: 20 },
  { subjectId: "INCOME_SUBSIDY", label: "補助金", categoryId: "income_subsidy_grant", type: "income", sortOrder: 30 },
  { subjectId: "INCOME_GRANT", label: "助成金", categoryId: "income_subsidy_grant", type: "income", sortOrder: 40 },
  { subjectId: "INCOME_HONORARIUM", label: "謝礼金", categoryId: "income_honorarium", type: "income", sortOrder: 50 },
  { subjectId: "INCOME_INTEREST", label: "受取利息", categoryId: "income_interest", type: "income", sortOrder: 60 },
  { subjectId: "INCOME_MISC", label: "雑収入", categoryId: "income_misc", type: "income", sortOrder: 70 },

  {
    subjectId: "EXPENSE_INSTRUCTOR_HONORARIUM",
    label: "講師謝礼金",
    categoryId: "expense_instructor",
    type: "expense",
    sortOrder: 110,
  },
  {
    subjectId: "EXPENSE_INSTRUCTOR_OTHER",
    label: "講師・その他",
    categoryId: "expense_instructor",
    type: "expense",
    sortOrder: 120,
  },
  {
    subjectId: "EXPENSE_SCORE_PURCHASE",
    label: "楽譜購入費",
    categoryId: "expense_instrument_supply",
    type: "expense",
    sortOrder: 130,
  },
  {
    subjectId: "EXPENSE_INSTRUMENT_ACCESSORY",
    label: "楽器付属品購入費",
    categoryId: "expense_instrument_supply",
    type: "expense",
    sortOrder: 140,
  },
  {
    subjectId: "EXPENSE_INSTRUMENT_REPAIR",
    label: "楽器修理費",
    categoryId: "expense_instrument_supply",
    type: "expense",
    sortOrder: 150,
  },
  {
    subjectId: "EXPENSE_FACILITY_FEE",
    label: "施設使用料",
    categoryId: "expense_concert",
    type: "expense",
    sortOrder: 160,
  },
  {
    subjectId: "EXPENSE_CONTEST_FEE",
    label: "大会参加費",
    categoryId: "expense_concert",
    type: "expense",
    sortOrder: 170,
  },
  {
    subjectId: "EXPENSE_INSTRUMENT_TRANSPORT",
    label: "楽器運搬費",
    categoryId: "expense_concert",
    type: "expense",
    sortOrder: 180,
  },
  {
    subjectId: "EXPENSE_CONCERT_MISC",
    label: "大会・演奏会雑費",
    categoryId: "expense_concert",
    type: "expense",
    sortOrder: 190,
  },
  {
    subjectId: "EXPENSE_BAND_FEDERATION_FEE",
    label: "吹奏楽連盟費",
    categoryId: "expense_burden",
    type: "expense",
    sortOrder: 200,
  },
  {
    subjectId: "EXPENSE_INSURANCE",
    label: "保険料",
    categoryId: "expense_insurance",
    type: "expense",
    sortOrder: 210,
  },
  {
    subjectId: "EXPENSE_SUPPLIES",
    label: "消耗品費",
    categoryId: "expense_misc",
    type: "expense",
    sortOrder: 220,
  },
  {
    subjectId: "EXPENSE_PRINTING",
    label: "印刷費",
    categoryId: "expense_misc",
    type: "expense",
    sortOrder: 230,
  },
  {
    subjectId: "EXPENSE_TRAVEL",
    label: "旅費・交通費",
    categoryId: "expense_misc",
    type: "expense",
    sortOrder: 240,
  },
  {
    subjectId: "EXPENSE_CEREMONIAL",
    label: "慶弔・交際費",
    categoryId: "expense_misc",
    type: "expense",
    sortOrder: 250,
  },
  {
    subjectId: "EXPENSE_MISC",
    label: "雑費",
    categoryId: "expense_misc",
    type: "expense",
    sortOrder: 260,
  },
];
